version: "3.5"
services:
 db:
   image: postgres
   environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
   env_file:
      - ../.env
   volumes:
      - ./pg_database-data:/var/lib/postgresql/data

 app:
   depends_on:
      - db
   build:
    context: ..
    dockerfile: ./docker/Dockerfile
   ports:
      - "3000:3000"
   environment:
     DB_HOST: db
   env_file:
      - ../.env
   volumes:
      - "../.:/app"

volumes:
 db:
